### ISSUE TITLE
QUALIFY clause without WHERE, GROUP BY or HAVING

### ISSUE THREAD

**Issue by pgrivachev** [google/zetasql#115]
I found that in BigQuery it is possible to use `QUALIFY` clause without `WHERE` or `GROUP BY` or `HAVING` clause.

But when I try to analyze the same query using ZetaSQL it returns the error:
```
"QUALIFY clause must be used in conjunction with WHERE or GROUP BY or HAVING clause"
```
 Is it a limitation or bug in ZetaSQL?

![image](https://user-images.githubusercontent.com/3650304/183750868-9ea63bd6-4eef-47c4-bbc9-005e5e0d6b1e.png)

**Comment by matthewcbrown** [comment]
QUALIFY is a weird one, since it has some backwards compatibility issues. You must both enable the language feature:
FEATURE_V_1_3_QUALIFY

But also set "QUALIFY" as a reserved keyword:
c++: https://github.com/google/zetasql/blob/1933acefe8eb10e293309a9fa7d7c7f1cb6bf8c4/zetasql/public/language_options.h#L273

java:
<uh...I guess you can't do this from java right now?! >

**Comment by pgrivachev** [comment]
Thank you @matthewcbrown, adding "QUALIFY" to reserved keywords helped.
